#spring:
#  application:
#    name: config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/LangJianHui/springcloudconfig.git
#  profiles:
#    active:
#server:
#  port: 9000
spring:
  profiles:
    active:
      -dev

spring:
  profiles: dev
  application:
    name: dev1

spring:
    profiles: test
    application:
      name: test1
